# Generated by Django 2.2.2 on 2019-07-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SizeTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('width', models.IntegerField()),
                ('hight', models.IntegerField()),
            ],
        ),
    ]
