version: '3'
services:
  django:
    build: .
    restart: always
    ports:
      - 80:8000
    volumes:
      - ./src:/app
    tty: true
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:306
    volumes:
      - ./data:/var/lib/mysql
    container_name: maria
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cocktail
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: --innodb-flush-method=O_DSYNC

