version: '3'
services:
  django:
    build: .
    restart: always
    ports:
      - 80:8000
    volumes:
      - ./src:/app
    command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
