@startuml

title main

Object スタートページ
Object ログインページ

note left of ログインページ
ナビバーから常にログアウトが可能
end note

package "scene" <<frame>> {
  Object シーン一覧ページ
}

package "user" <<frame>> {
  Object 会員情報変更ページ
  Object パスワード変更ページ
  Object 退会ページ

  note left of 会員情報変更ページ
    ナビバーから常にアクセス可能
  end note

  note left of user
    userアプリケーション内は
    互いにサイドバーから遷移可能
  end note
}


' フィールド定義
シーン一覧ページ : 要ログイン
会員情報変更ページ : 要ログイン
会員情報変更ページ : 組織名, メールアドレス変更

' 遷移
' - メイン遷移
スタートページ -down-> ログインページ
ログインページ --down> シーン一覧ページ
' - 会員情報変更遷移
scene--> 会員情報変更ページ
退会ページ -up-> "退会" スタートページ

@enduml
