@startuml main
Object スタートページ    
Object ログインページ
Object 新規登録ページ


package "会員" <<frame>> {
    Object ログアウトページ
    Object 退会ページ
}

package "シーン" <<frame>> {
    Object シーン一覧ページ
}


note right of 会員
    会員ページ
    プラグイン管理ページ
    シーン管理ページは
    互いに遷移可能
end note


ログアウトページ : 要ログイン

ログインページ --> シーン一覧ページ

スタートページ --> ログインページ
スタートページ --> 新規登録ページ
新規登録ページ  -->  ログインページ
ログアウトページ --> ログインページ
退会ページ --> スタートページ


note left of ログインページ
    
	要ログインページは非ログイン時、
	ログインページにリダイレクトする

end note
@enduml