@startuml main
Object スタートページ    
Object ログインページ
Object 新規登録ページ
Object シーン一覧ページ


package "会員" <<frame>> {
}

package "シーン" <<frame>> {
}

package "シーン管理" {

    Object シーン表示ページ
    Object シーン編集ページ
}

note right of 会員
    会員ページ
    プラグイン管理ページ
    シーン管理ページは
    互いに遷移可能
end note


ログアウトページ : 要ログイン
プラグイン管理ページ : 要ログイン
シーン表示ページ : 要ログイン
シーン編集ページ : 要ログイン

ログインページ --> シーン

スタートページ --> ログインページ
スタートページ --> 新規登録ページ
新規登録ページ  -->  ログインページ
ログアウトページ -left-> スタートページ

会員ページ --> プラグイン管理ページ
プラグイン管理ページ --> 会員ページ

会員 -left-> ログアウトページ


退会ページ -up-> スタートページ

note left of ログインページ
    
	要ログインページは非ログイン時、
	ログインページにリダイレクトする

end note
@enduml