@startuml

title scene

Object ログインページ

package "scene : 要ログイン" {
    Object シーン一覧
    Object シーン管理
    Object シーン表示
    Object シーン編集
}

package "user : 要ログイン" {
    Object 会員ページ 
}

'遷移
' - メイン遷移
シーン一覧 --> シーン管理
シーン管理 -up-> シーン一覧
シーン一覧 --> シーン表示
シーン管理 --> シーン編集

'他機能遷移
ログインページ --> シーン一覧
ログインページ --> 会員ページ
シーン一覧 --> 会員ページ
会員ページ --> シーン一覧


note left of シーン管理 {
    各シーンごとの
    CRUD処理..etcをするページ
} 

@enduml