@startuml

title user

Object スタートページ
Object ログインページ

package "scene" <<frame>> {
    Object シーン一覧ページ
}

package "user" <<frame>> {
    Object 会員ページ
    Object ログアウトページ

    Object 会員情報変更ページ
    Object パスワード変更ページ
    Object メールアドレス変更ページ
    Object 退会ページ
}


' フィールド定義
会員ページ : 要ログイン
会員情報変更ページ : 要ログイン
メールアドレス変更ページ : 要ログイン
パスワード変更ページ : 要ログイン
退会ページ : 要ログイン

' 遷移
' - メイン遷移
スタートページ --> ログインページ
ログインページ --> シーン一覧ページ

' - 会員情報変更遷移
シーン一覧ページ --> 会員ページ
会員ページ --> 会員情報変更ページ
会員情報変更ページ --> メールアドレス変更ページ
会員情報変更ページ --> パスワード変更ページ
会員情報変更ページ --> 退会ページ
メールアドレス変更ページ --> 会員情報変更ページ
パスワード変更ページ --> 会員情報変更ページ

' - ログアウト遷移 
会員ページ --> ログアウトページ
ログアウトページ --> ログインページ

' - 退会遷移
退会ページ -down-> スタートページ

@enduml
